name: matrical
description: "Pre-enrollment tool for UPRM Students."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.4
  calendar_view: ^1.1.0
  cloud_firestore: ^5.0.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5
  feedback: ^3.0.0
  firebase_core: ^3.1.0

  flutter_bloc: ^8.1.6
  flutter_email_sender: ^6.0.3
  gal: ^2.3.0
  go_router: ^14.2.0
  info_widget: ^1.0.0
  open_file: ^3.3.2
  pair: ^0.1.2
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  url_launcher: ^6.3.0
  icalendar:
    git:
      url: https://gitlab.com/alejandrocruzadoruiz/icalendar-dart.git
      ref: main # branch name
  universal_io: ^2.2.2
  archive: ^3.6.1
  web_browser_detect: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
