name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"

      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Enable Flutter Web
        run: |
          cd matrical
          flutter config --enable-web

      - name: Download Dependencies
        run: |
          cd matrical
          flutter pub get

      - name: Build
        run: |
          cd matrical
          flutter build web --web-renderer canvaskit
          cp -avr ./build/web/* ../

      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Actions] Publish updated build artifacts"
          push_options: "--force"
          branch: web-builds
          create_branch: true
